name: Execute Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GCP_PROJECT: ${{ vars.GCP_PROJECT }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
    - uses: actions/checkout@v4

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Lint with ruff
      run: |
        uv run --python ${{ matrix.python-version }} ruff check

    - name: Test with pytest
      run: |
        uv run --python ${{ matrix.python-version }} pytest
